# Use a imagem oficial do Node.js
FROM node:20.11.1

# Defina o diretório de trabalho dentro do container
WORKDIR /Backend

# Copie os arquivos package.json e package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Exponha a porta que a aplicação vai usar
EXPOSE 8080

# Defina o comando para iniciar a aplicação
CMD ["npm", "start"]
